Algoritmo "Apresentar os quadrados dos números inteiros de 15 a 200"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Mauricio
// Data atual  : 29/09/2024
Var
   num, quadrado : inteiro
Inicio
   Para num de 15 ate 200 faca
      quadrado <- num * num
      Escreva("O quadrado de ", num, " é: ", quadrado)
   FimPara
Fimalgoritmo
