Algoritmo "Apresentar todos os números divisíveis por 4 menores que 200"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Apresentar todos os números divisíveis por 4 menores que 200
// Autor(a)    : Mauricio
// Data atual  : 29/09/2024
Var
   num : inteiro
Inicio
   Para num de 1 ate 199 faca
      Se (num % 4 = 0) Entao
         Escreva(num)
      FimSe
   FimPara
Fimalgoritmo
