Algoritmo "Conversão de graus Celsius para Fahrenheit de 10 em 10 graus"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Conversão de graus Celsius para Fahrenheit de 10 em 10 graus
// Autor(a)    : Mauricio
// Data atual  : 29/09/2024
Var
   celsius, fahrenheit : real
Inicio
   Para celsius de 10 ate 100 passo 10 faca
      fahrenheit <- (9 * celsius + 160) / 5
      Escreva(celsius, "°C = ", fahrenheit, "°F")
   FimPara
Fimalgoritmo
