Algoritmo "Resultados das potências de 3 variando do expoente 0 até o 15"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Resultados das potências de 3 variando do expoente 0 até o 15
// Autor(a)    : Mauricio
// Data atual  : 29/09/2024
Var
   expoente, potencia : inteiro
Inicio
   potencia <- 1
   Para expoente de 0 ate 15 faca
      Escreva("3^", expoente, " = ", potencia)
      potencia <- potencia * 3
   FimPara
Fimalgoritmo
