Algoritmo "Soma dos cem primeiros números inteiros"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Soma dos cem primeiros números inteiros
// Autor(a)    : Mauricio
// Data atual  : 29/09/2024
Var
   num, soma : inteiro
Inicio
   soma <- 0
   Para num de 1 ate 100 faca
      soma <- soma + num
   FimPara
   Escreva("A soma dos cem primeiros números inteiros é: ", soma)
Fimalgoritmo
